import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Poppins } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo.ico" }],
};



const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // pilih sesuai kebutuhan
})

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${poppins.className}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
