export const seedDefaultPlans = [
    {
        name: "FREE",
        displayName: "Free",
        description: "Paket gratis untuk mencoba fitur dasar Zosmed.",
        price: 0,
        period: "LIFETIME" as const,
        color: "from-gray-500 to-gray-600",
        bgColor: "bg-gray-50",
        borderColor: "border-gray-200",
        maxAccounts: 1,
        maxDMPerMonth: 100,
        maxAIReplyPerMonth: 20,
        features: {
            included: [
                "1 akun Instagram",
                "100 auto-reply per bulan",
                "20 AI-powered reply",
                "Template Workflow",
            ],
            notIncluded: [
                "Advanced Analytics Dashboard",
                "Priority support",
                "Lead scoring",
            ],
        },
        sortOrder: 0,
    },
    {
        name: "STARTER",
        displayName: "Starter",
        description: "Cocok untuk UMKM atau individu yang ingin mengotomatisasi DM dan respon.",
        price: 149000,
        period: "MONTHLY" as const,
        color: "from-blue-500 to-cyan-500",
        bgColor: "bg-blue-50",
        borderColor: "border-blue-200",
        popular: true,
        badge: "MOST POPULAR",
        maxAccounts: 3,
        maxDMPerMonth: 2000,
        maxAIReplyPerMonth: 500,
        features: {
            included: [
                "3 akun Business Instagram",
                "2000 auto-reply per bulan",
                "500 AI-powered reply",
                "Template Workflow",
                "AI intent detection",
                "Advanced Analytics Dashboard",
            ],
            notIncluded: ["Lead scoring", "Priority support"],
        },
        sortOrder: 1,
    },
    {
        name: "PRO",
        displayName: "Pro",
        description: "Untuk agensi atau bisnis besar yang butuh performa tinggi dan fitur lengkap.",
        price: 399000,
        period: "MONTHLY" as const,
        color: "from-purple-500 to-pink-500",
        bgColor: "bg-purple-50",
        borderColor: "border-purple-200",
        maxAccounts: 5,
        maxDMPerMonth: 10000,
        maxAIReplyPerMonth: 2000,
        features: {
            included: [
                "5 akun Business Instagram",
                "10.000 auto-reply per bulan",
                "2000 AI-powered reply",
                "Template Workflow",
                "AI intent detection",
                "Advanced Analytics Dashboard",
                "Lead scoring",
                "Priority support",
            ],
            notIncluded: [],
        },
        sortOrder: 2,
    },
];
